export const errorCodes = {
    NOT_FOUND: "NOT_FOUND",
    UNAUTHORIZED: "UNAUTHORIZED",
    FORBIDDEN: "FORBIDDEN",
    SERVER_ERROR: "SERVER_ERROR",
    UNAUTHENTICATED: "UNAUTHENTICATED",
    BAD_USER_INPUT: "BAD_USER_INPUT",
    VALIDATION_ERROR: "VALIDATION_ERROR",
    CONFLICT: "CONFLICT",
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
  };
  